/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package edu.austral.dissis.starships.app

import javafx.application.Application.launch

fun main() {
    launch(Game::class.java)
}
